<?php
namespace it_hive\core\AdminBox;

abstract class OptionsPage extends Box {

	protected $loadingHook = ' ';

	const defaults = array(
		'source'		=> 'option',
		'pageLocation'	=> 'themes.php'
	);

	const exclude = parent::exclude + self::defaults;

	function __construct( $params ) {
		$this->params = array_merge(self::defaults,$params);
		$this->name = $this->params['name'];
		parent::__construct( $this->params );
	}

	protected function addActions() {
		add_action( 'admin_menu', array( $this,'addMenuPage' ) );
	}

	public function addMenuPage() {
		$this->loadingHook = \add_submenu_page(
			$this->params['pageLocation'],
			$this->params['title'],
			$this->params['title'],
			'edit_theme_options',
			$this->name,
			array( $this,'show' ) );
		add_action( 'load-' . $this->loadingHook, array( $this, 'save' ) );
	}

	public function save() {
		$_POST = stripslashes_deep($_POST);
		if( parent::save() ) {
			$this->redirect();
		}
	}

	public function show() {
		echo( '<form method="post" action="">'."\n" );
		parent::show(); // TODO: Change the autogenerated stub
		echo( '</form>'."\n" );
	}

	protected function redirect() {
		wp_redirect( $_SERVER['REQUEST_URI'] );
		exit();
	}
}