<?php
namespace it_hive\core\AdminBox;

abstract class UserBox extends Box {
    const defaults = array(
        'source'		=> 'userMeta',
        'sourceObject'  => 0
    );

    const exclude = parent::exclude + self::defaults;

    protected static $counter = 1;

    function __construct( $params ) {
        $this->params = array_merge(self::defaults,$params);
        $this->name = $this->params['name'];
        parent::__construct( $this->params );
    }

    protected function addActions() {
        add_action( 'edit_user_profile', array($this,'show'));
        add_action( 'show_user_profile', array($this,'show'));
        add_action( 'personal_options_update', array( $this, 'save') );
        add_action( 'edit_user_profile_update', array( $this, 'save') );
    }

    public function show( $user =null,$args=[] ) {
        $this->params['sourceObject'] = $user->ID;
        parent::show();
    }

    public function save( $id = 0 ) {
        if (!current_user_can('edit_user', $id)) {
            return false;
        }
        $this->params['sourceObject'] = $id;
        parent::save();
    }

    public function display($skin = null, $user = 0){
        if(!$user){
            $user = get_current_user_id();
        }
        $this->params['sourceObject'] = $user;
        parent::display($skin);
    }

    public function render() {
        return '<div class="metabox theme-postbox" data-control-type="box">' .parent::render() . '</div>'; // TODO: Change the autogenerated stub
    }
}