<?php
namespace it_hive\core\Blocks\image\picture;
use \it_hive\THEME;

class Block extends \it_hive\core\Blocks\group\Block {

	const hiddenDefaults = array(
		'sources' => array()
	);

	const defaults = array(
	    'value' => []
	) + self::hiddenDefaults;

	const exclude = parent::exclude + self::hiddenDefaults;

	public function __construct( $params ) {
		$this->params = array_merge( self::defaults, $params );
		parent::__construct( $this->params );
	}

	protected function CreateChildren() {
		$data                              = $this->get();
		$sources                           = $this->params['sources'];
		$this->params['children']['image'] = array(
			'value'      => $data['image'],
			'type'       => 'image',
			'textUpload' => __( 'Set Image', THEME::$textdomain ),
			'label'      => $this->params['label']
		);
		foreach ( $sources as $name => $source ) {
			$source['label'] ? $label = $source['label'] : $label=$name;
			$this->params['children'][ $name ] = array(
				'value'      => $data[ $name ],
				'type'       => 'image',
				'textUpload' => __( 'Set Source', THEME::$textdomain ),
				'label'      => $label
			);
		}
		parent::CreateChildren(); // TODO: Change the autogenerated stub
	}
}